CREATE TABLE SOP.STA_MONEDA (
  CMONEDDESCRIP VARCHAR2(50 BYTE) NOT NULL,
  NMONEDFACTOR NUMBER(8, 6) DEFAULT (0) NOT NULL,
  CMONEDACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CCODIGO_MONEDA CHAR(3 BYTE),
  NID_MONEDA NUMBER(5, 0) NOT NULL,
  NID_VIGENCIA NUMBER(5, 0),
  CONSTRAINT PX_STAMONEDA PRIMARY KEY (NID_MONEDA))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 16K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;