CREATE TABLE SOP.SOPDEPADUANAS (
  CADUACODIGO CHAR(3 BYTE) NOT NULL,
  CADUADESCRIP VARCHAR2(50 BYTE),
  CADUAACTIVO CHAR(1 BYTE),
  CONSTRAINT PK__SOPDEPADUANAS__1B0907CE PRIMARY KEY (CADUACODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;