CREATE TABLE SOP.SOPOFICINA (
  COFICICODIGO CHAR(4 BYTE) NOT NULL,
  COFICITIPO CHAR(1 BYTE) DEFAULT ('E'),
  COFICITIPONAC CHAR(7 BYTE),
  COFICISIGLA CHAR(6 BYTE),
  CPAISCODIGO CHAR(3 BYTE),
  COFICINOMBRE VARCHAR2(70 BYTE),
  COFICIDESCADM VARCHAR2(70 BYTE),
  COFICIACTIVO CHAR(1 BYTE),
  COFICICATEGC VARCHAR2(6 BYTE),
  COFICISUBCLA VARCHAR2(6 BYTE),
  COFICINOMCOR VARCHAR2(25 BYTE),
  COFICILLEGAA NUMBER(10, 0) DEFAULT (0) NOT NULL,
  COFICILLEGAC NUMBER(10, 0) DEFAULT (0) NOT NULL,
  COFICICUOTA NUMBER(18, 2),
  COFICIPTOCAJA CHAR(1 BYTE) DEFAULT (0),
  COFICIPTODESP CHAR(1 BYTE) DEFAULT (0),
  COFICIPTOVENTA CHAR(1 BYTE) DEFAULT (0),
  COFICIPTODISTRIB CHAR(1 BYTE) DEFAULT (0),
  CTPVCODIGO CHAR(4 BYTE),
  NCRPCODIGO NUMBER(10, 0),
  COFICIDIRECC VARCHAR2(150 BYTE),
  COFICITELF VARCHAR2(20 BYTE),
  COFICIEMAIL VARCHAR2(50 BYTE),
  COFICISUCSIM VARCHAR2(3 BYTE),
  COFICFILATELIA CHAR(1 BYTE),
  COFICDEPENDE CHAR(4 BYTE),
  COFICIENLINEA CHAR(1 BYTE),
  COFICICCPL CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  COFIATENCION VARCHAR2(6 BYTE),
  COFICIDESADUNAJE CHAR(5 BYTE),
  COFICISERIEEXPRESO CHAR(2 BYTE),
  COFICISSAP CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  COFICIAPARTADOS CHAR(3 BYTE),
  CFLAGUPDATETBL CHAR(1 BYTE),
  COFICIFLAGEXF CHAR(1 BYTE),
  COFICILUGAR VARCHAR2(10 BYTE),
  COFICIFLAGSOAT CHAR(1 BYTE) DEFAULT ('N'),
  COFICILINEADED CHAR(1 BYTE),
  COFICIZONA CHAR(1 BYTE),
  COFICISIGLASOLD VARCHAR2(3 BYTE),
  COFICIBOVEDA CHAR(1 BYTE),
  PREINI CHAR(2 BYTE),
  PREFIN CHAR(2 BYTE),
  NOMTAB VARCHAR2(50 BYTE),
  CONSTRAINT PK_SOPOFICINA_COFICICODIGO PRIMARY KEY (COFICICODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE INDEX SOP.SOP_IND02_4 ON SOP.SOPOFICINA (COFICISIGLA)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND03_2 ON SOP.SOPOFICINA (COFICISIGLA, COFICITIPO)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND04_1 ON SOP.SOPOFICINA (COFICITIPO)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND05 ON SOP.SOPOFICINA (COFICICCPL)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND06 ON SOP.SOPOFICINA (COFICDEPENDE)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;

COMMENT ON COLUMN SOP.SOPOFICINA.COFICICODIGO IS 'LLAVE PRIMARIA';