CREATE TABLE SOP.ADMAGENTEPOSTAL (
  CAGENREFE NUMBER(19, 0) NOT NULL,
  CAGENNOMBRE VARCHAR2(80 BYTE),
  COFICICODIGO CHAR(4 BYTE),
  CAGENACTIVO CHAR(1 BYTE) DEFAULT (0) NOT NULL,
  CAGENCREA CHAR(6 BYTE),
  CAGENDCREA DATE DEFAULT (SYSDATE) NOT NULL,
  CAGENMODI CHAR(6 BYTE),
  CAGENDMODI DATE,
  CONSTRAINT PK_ADMAGENTEPOSTAL PRIMARY KEY (CAGENREFE))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;