CREATE TABLE SOP.SOPGRUPO (
  CAGRUPCODIGO CHAR(2 BYTE) NOT NULL,
  CAGRUPNOMBRE VARCHAR2(100 BYTE) NOT NULL,
  CAGRUPACTIVO CHAR(1 BYTE) DEFAULT (' '),
  CONSTRAINT PK_SOPGRUPO_CAGRUPCODIGO PRIMARY KEY (CAGRUPCODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;