CREATE TABLE SOP.SOPMENSAJERO (
  CMENSAREFE CHAR(10 BYTE) NOT NULL,
  CMENSACODIGO CHAR(6 BYTE),
  CMENSANOMBRE VARCHAR2(50 BYTE),
  CMENSAACTIVO CHAR(1 BYTE) NOT NULL,
  CMENSAUSUCREA CHAR(6 BYTE),
  CMENSAFECCREA DATE DEFAULT (SYSDATE) NOT NULL,
  CMENSAUSUMODI CHAR(6 BYTE),
  CMENSAFECMODI DATE DEFAULT (SYSDATE) NOT NULL,
  COFICICODIGO CHAR(4 BYTE) DEFAULT ('2201') NOT NULL,
  DNI VARCHAR2(8 BYTE),
  SPRINT VARCHAR2(12 BYTE),
  CONSTRAINT PK_SOPMENSAJERO PRIMARY KEY (CMENSAREFE),
  CONSTRAINT UNK_CMENSACODIGO UNIQUE (CMENSACODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;