CREATE TABLE SOP.STA_ESTADO_ORDEN (
  NID_ESTADO NUMBER(5, 0) NOT NULL,
  CDESC_ESTADO VARCHAR2(60 BYTE) NOT NULL,
  CFLAG_ESTADO CHAR(1 BYTE) NOT NULL,
  CCOD_ESTADO CHAR(5 BYTE),
  CONSTRAINT PK_NID_ESTADO PRIMARY KEY (NID_ESTADO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;