CREATE TABLE SOP.SOPEVENTO (
  CEVENTCODIGO CHAR(3 BYTE) NOT NULL,
  CEVENTSIGLA CHAR(3 BYTE),
  CEVENTDESCRIP VARCHAR2(50 BYTE),
  CEVENTTIPO CHAR(1 BYTE) NOT NULL,
  CEVENTACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CEVENTIPS CHAR(5 BYTE),
  CONSTRAINT PK_SOPEVENTORECLAM_CEVENTCODI PRIMARY KEY (CEVENTCODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;