CREATE TABLE SOP.STA_MODALIDAD (
  NID_MODALIDAD NUMBER(5, 0) NOT NULL,
  CDES_MODALIDAD VARCHAR2(60 BYTE),
  CMOD_VIGENTE CHAR(1 BYTE) NOT NULL,
  CONSTRAINT PK_NID_MODALIDAD PRIMARY KEY (NID_MODALIDAD))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;