CREATE TABLE SOP.SOPTRANSPORTISTA (
  CTRANSCODIGO CHAR(4 BYTE) NOT NULL,
  CTRANSSIGLA CHAR(4 BYTE) NOT NULL,
  CTRANSNOMBRE VARCHAR2(80 BYTE) NOT NULL,
  CTRANSDIREC VARCHAR2(80 BYTE),
  CTRANSTELEF1 VARCHAR2(10 BYTE),
  CTRANSTELEF2 VARCHAR2(10 BYTE),
  CTRANSRUC CHAR(11 BYTE),
  CTRANSFAX VARCHAR2(10 BYTE),
  CTRANSEMAIL VARCHAR2(40 BYTE),
  CTRANSATENCION VARCHAR2(50 BYTE),
  CTRANSTIPO CHAR(1 BYTE) NOT NULL,
  CTRANSACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CTRANSTARIFMONE CHAR(3 BYTE) DEFAULT ('DOL') NOT NULL,
  CONSTRAINT PK__SOPTRANSPORTISTA__2A4B4B5E PRIMARY KEY (CTRANSCODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;