CREATE TABLE SOP.SOPCATEGCORREO (
  CCATEGCODIGO CHAR(2 BYTE) NOT NULL,
  CCATEGSIGLAS CHAR(1 BYTE) NOT NULL,
  CCATEGDESCRIP VARCHAR2(50 BYTE) NOT NULL,
  CCATEGACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CCATEGNOMCOR CHAR(6 BYTE),
  CONSTRAINT PK__SOPCATC__4AB81AF0 PRIMARY KEY (CCATEGCODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;