CREATE TABLE SOP.SOPDESPACHOTIPO (
  CTDESPCODI CHAR(1 BYTE) NOT NULL,
  CTDESPNOMB CHAR(30 BYTE) NOT NULL,
  CONSTRAINT PK_SOPDESPACHOTIPO PRIMARY KEY (CTDESPCODI))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;