CREATE TABLE SOP.SOPUSUARIO (
  IDUSUARIO CHAR(12 BYTE) NOT NULL,
  CNOMUSUA VARCHAR2(50 BYTE),
  CCLAVE VARCHAR2(12 BYTE),
  CACTIVO CHAR(1 BYTE),
  NNIVEL NUMBER(10, 0),
  FLAGCUADRODIST CHAR(2 BYTE),
  CAREA CHAR(4 BYTE),
  CUSUSESION CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  CCLAVENEW VARCHAR2(12 BYTE),
  CODSUC CHAR(4 BYTE),
  COFICICODIGO CHAR(4 BYTE),
  CTURNO CHAR(1 BYTE),
  CTIPUSUCODI NUMBER(10, 0),
  CLAVENUEVA VARCHAR2(12 BYTE),
  CONSTRAINT PK_SOPUSUARIO_IDUSUARIO PRIMARY KEY (IDUSUARIO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;