CREATE TABLE SOP.SOPSERVICIO (
  CSERVICODIGO CHAR(2 BYTE) NOT NULL,
  CSERVTIPO CHAR(1 BYTE) DEFAULT ('E') NOT NULL,
  CSERVIDESCRIP VARCHAR2(50 BYTE) NOT NULL,
  CSERVIACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CONSTRAINT PK_SOPSERVICIO_CSERVICODIGO PRIMARY KEY (CSERVICODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;