CREATE TABLE SOP.SOPMONEDA (
  CMONEDCODIGO CHAR(3 BYTE) NOT NULL,
  CMONEDDESCRIP VARCHAR2(50 BYTE) NOT NULL,
  NMONEDFACTOR NUMBER(8, 6) DEFAULT (0) NOT NULL,
  CMONEDACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CONSTRAINT PK_SOPMONEDA PRIMARY KEY (CMONEDCODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;