CREATE TABLE SOP.SOPCUADROS (
  CCUADROCODIGO CHAR(2 BYTE) NOT NULL,
  CCUADRONOMBRE VARCHAR2(50 BYTE),
  CCUADROTIPO CHAR(1 BYTE),
  CCUADROACTIVO CHAR(1 BYTE),
  CDESTIPOCOB CHAR(1 BYTE),
  CSERCODIGO CHAR(5 BYTE),
  CONSTRAINT PK_SOPCUADROS PRIMARY KEY (CCUADROCODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;