CREATE TABLE SOP.SOPTRACKING (
  CTRACKNUMERO CHAR(14 BYTE) NOT NULL,
  CDESPAREFE CHAR(14 BYTE),
  CENVIOREFE CHAR(12 BYTE),
  CEVENTCODIGO CHAR(3 BYTE),
  CTRACKFECEVE CHAR(10 BYTE) NOT NULL,
  CTRACKHOREVE CHAR(5 BYTE) NOT NULL,
  CTRACKNROLIST CHAR(2 BYTE),
  CTRACKNROORD CHAR(2 BYTE),
  CTRACKLISTCLOS CHAR(1 BYTE),
  CTRACKOFICINA CHAR(4 BYTE),
  ESTADO CHAR(1 BYTE) NOT NULL,
  CPAISORIGEN CHAR(3 BYTE),
  CPAISDESTINO CHAR(3 BYTE),
  COFICORIGEN CHAR(4 BYTE),
  COFICDESTINO CHAR(4 BYTE),
  CENVFLEMPRESAR CHAR(1 BYTE),
  CENVFLRETENIDO CHAR(1 BYTE),
  CENVFLAFORABLE CHAR(1 BYTE),
  CENVFLACTACONF CHAR(1 BYTE),
  CENVADUANCOD CHAR(3 BYTE),
  CENVTIPAQCOD CHAR(2 BYTE),
  CENVTIPOCOD CHAR(2 BYTE),
  CENVCLIECOD CHAR(3 BYTE),
  CENVGRUPOCOD CHAR(2 BYTE),
  CENVCLASECOD CHAR(1 BYTE),
  CTRACKFLAGDIST CHAR(1 BYTE),
  CDISTNUMERO CHAR(8 BYTE),
  CTRACKDESPACHO CHAR(14 BYTE),
  CSECTREFE NUMBER(10, 0),
  CMENSAREFE CHAR(10 BYTE),
  CDISTDESTINATARIO VARCHAR2(80 BYTE),
  CDISTDIRECCION VARCHAR2(100 BYTE),
  NDISTPESO NUMBER(10, 0),
  NDISTVISITA NUMBER(10, 0),
  CMOTCODIGO CHAR(2 BYTE),
  CDISTHORENTRE CHAR(5 BYTE),
  CDISTRECIBIDOPOR VARCHAR2(50 BYTE),
  CDOCIDECODIGO CHAR(2 BYTE),
  CDISTNRODOCENT VARCHAR2(11 BYTE),
  CDISTOBSENTRE VARCHAR2(100 BYTE),
  CDISTFLAGREZAGO NUMBER(10, 0),
  CTRACKNUMORIG CHAR(14 BYTE),
  CUBIGECODIGO CHAR(6 BYTE),
  CPAISDESTINOENV CHAR(3 BYTE),
  CODBARRA CHAR(18 BYTE),
  CFLAGEMPGLOB CHAR(1 BYTE),
  CONSTRAINT CTRACKNUMERO PRIMARY KEY (CTRACKNUMERO),
  CONSTRAINT FK_SOPTRACKING_SOPDESPACHO FOREIGN KEY (CDESPAREFE)
    REFERENCES SOP.SOPDESPACHO(CDESPAREFE) ON DELETE CASCADE,
  CONSTRAINT FK_SOPTRACKING_SOPENVIOS FOREIGN KEY (CENVIOREFE)
    REFERENCES SOP.SOPENVIOS(CENVIOREFE) ON DELETE CASCADE DISABLE,
  CONSTRAINT FK_SOPTRACKING_SOPEVENTO FOREIGN KEY (CEVENTCODIGO)
    REFERENCES SOP.SOPEVENTO(CEVENTCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPTRACKING_SOPOFICINA FOREIGN KEY (CTRACKOFICINA)
    REFERENCES SOP.SOPOFICINA(COFICICODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPTRACKING_SOPSECTOR FOREIGN KEY (CSECTREFE)
    REFERENCES SOP.SOPSECTOR(CSECTREFE) ON DELETE CASCADE)
TABLESPACE SOP_DATA2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
LOGGING
ENABLE ROW MOVEMENT;

CREATE INDEX SOP.ID_TRACK04 ON SOP.SOPTRACKING (CEVENTCODIGO, ESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK05 ON SOP.SOPTRACKING (CDESPAREFE, CENVIOREFE)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK07 ON SOP.SOPTRACKING (CENVIOREFE)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK08 ON SOP.SOPTRACKING (CDESPAREFE, CDISTNUMERO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK09 ON SOP.SOPTRACKING (CENVTIPOCOD, COFICDESTINO, CENVCLASECOD, ESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK10 ON SOP.SOPTRACKING (CENVFLEMPRESAR, CENVTIPOCOD, COFICDESTINO, ESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK11 ON SOP.SOPTRACKING (CENVFLAFORABLE, CENVGRUPOCOD, CENVTIPOCOD, CENVADUANCOD, ESTADO, COFICDESTINO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK12 ON SOP.SOPTRACKING (CENVFLAFORABLE, CENVTIPOCOD, COFICDESTINO, ESTADO, CENVFLACTACONF)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK13 ON SOP.SOPTRACKING (CENVTIPOCOD, COFICDESTINO, CENVCLASECOD, CENVFLRETENIDO, ESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK17 ON SOP.SOPTRACKING (CTRACKDESPACHO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK19 ON SOP.SOPTRACKING (CSECTREFE)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK20 ON SOP.SOPTRACKING (COFICDESTINO, CEVENTCODIGO, CTRACKFLAGDIST, CENVFLAFORABLE, CENVTIPOCOD)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.ID_TRACK22 ON SOP.SOPTRACKING (CDESPAREFE, CODBARRA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IDX$$_0E610001 ON SOP.SOPTRACKING (TRIM("CENVADUANCOD"), TRIM("CENVTIPOCOD"), ESTADO, CENVFLAFORABLE)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IDX24607_474DB0001 ON SOP.SOPTRACKING (COFICDESTINO, CTRACKFECEVE, CEVENTCODIGO, CENVTIPOCOD, CTRACKFLAGDIST)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE INDEX SOP.IDX24607_474DD0001 ON SOP.SOPTRACKING (COFICDESTINO, CTRACKFECEVE, CEVENTCODIGO, CTRACKFLAGDIST)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE INDEX SOP.IX_TRACK21 ON SOP.SOPTRACKING (CDISTNUMERO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;