CREATE TABLE SOP.SOPPAISES (
  CPAISCODIGO CHAR(3 BYTE) NOT NULL,
  CPAISCODONU CHAR(2 BYTE) NOT NULL,
  CPAISDESCRIP VARCHAR2(65 BYTE) NOT NULL,
  CPAISIDIOMA CHAR(1 BYTE),
  CPAISGRUPO CHAR(2 BYTE),
  CPAISCODADUA CHAR(3 BYTE),
  CPAISACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CPAISPAGWEB VARCHAR2(70 BYTE),
  CMONEDCODIGO CHAR(3 BYTE),
  CPAISINTERCAMB CHAR(1 BYTE) DEFAULT (' ') NOT NULL,
  CPAISNUMTRAMS NUMBER(10, 0) DEFAULT (0) NOT NULL,
  CPAISZONA CHAR(1 BYTE) DEFAULT ('6'),
  CPAISGRUPOSAL CHAR(2 BYTE),
  CPAISNOMBESP VARCHAR2(65 BYTE),
  CPAISNOMBING VARCHAR2(65 BYTE),
  CPAISNOMBFRA VARCHAR2(65 BYTE),
  CONSTRAINT PK_SOPPAISES PRIMARY KEY (CPAISCODIGO),
  CONSTRAINT FK_SOPPAISES_SOPMONEDA FOREIGN KEY (CMONEDCODIGO)
    REFERENCES SOP.SOPMONEDA(CMONEDCODIGO) ON DELETE CASCADE)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE INDEX SOP.IX_CPAISCODONU ON SOP.SOPPAISES (CPAISCODONU)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;