CREATE TABLE SOP.STA_CLIENTE (
  NID_CLIENTE NUMBER(10, 0) NOT NULL,
  CTIPO_DOCUM CHAR(2 BYTE),
  CNRO_DOCUM VARCHAR2(15 BYTE),
  CRAZON_SOCIAL VARCHAR2(45 BYTE),
  CTIPO_CLIE CHAR(1 BYTE),
  CCOD_POSTAL CHAR(3 BYTE),
  COBSER VARCHAR2(25 BYTE),
  CESTADO VARCHAR2(10 BYTE),
  CFLAG_TADS CHAR(1 BYTE),
  CPAISCODIGO CHAR(3 BYTE) DEFAULT '207',
  CONSTRAINT PK_NID_CLIENTE PRIMARY KEY (NID_CLIENTE),
  CONSTRAINT FX_PAISE FOREIGN KEY (CPAISCODIGO)
    REFERENCES SOP.SOPPAISES(CPAISCODIGO))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;