CREATE TABLE SOP.SOPENVIOS (
  CENVIOREFE CHAR(12 BYTE) DEFAULT ('N') NOT NULL,
  CTIPOENVIO CHAR(2 BYTE) NOT NULL,
  CENVIOANIO CHAR(4 BYTE) NOT NULL,
  CPAISCODIGO CHAR(3 BYTE),
  CENVIOPPTIPO CHAR(1 BYTE) DEFAULT ('0') NOT NULL,
  CENVIOEXCENTO CHAR(1 BYTE),
  CENVIOESTADO CHAR(1 BYTE),
  CENVIOEMBOLSA CHAR(1 BYTE) DEFAULT ('0') NOT NULL,
  CENVIONROORIGEN CHAR(20 BYTE),
  CENVIONROAVISOLL CHAR(8 BYTE),
  CENVIOREMITEN VARCHAR2(80 BYTE),
  CENVIODIRREMITEN VARCHAR2(100 BYTE),
  CENVIOTELREMITEN VARCHAR2(15 BYTE),
  CENVIODNIREMITEN CHAR(10 BYTE),
  NENVIOPESOORIG NUMBER(18, 3),
  CENVIODESTINA VARCHAR2(80 BYTE),
  CENVIOTIPDESTINA CHAR(1 BYTE),
  CENVIODIRDESTINA VARCHAR2(100 BYTE),
  CENVIOTELDESTINA VARCHAR2(15 BYTE),
  CENVIODNIDESTINA CHAR(10 BYTE),
  CUBIGECODIGO CHAR(6 BYTE),
  CCODPOSTAL CHAR(4 BYTE),
  CENVIOCONTENIDO VARCHAR2(100 BYTE),
  CENVIOOBSERV VARCHAR2(100 BYTE),
  NENVIOPORTE NUMBER(18, 3) DEFAULT (0),
  NENVIOREPESADO NUMBER(18, 3),
  CENVIOFECLLEGA CHAR(10 BYTE),
  CTIPAQCODIGO CHAR(2 BYTE),
  NENVIOVALDECORIG NUMBER(18, 3),
  CENVIOANIOMAN CHAR(4 BYTE),
  CENVIONROMAN CHAR(5 BYTE),
  CENVIOFECAPERT CHAR(10 BYTE),
  CENVIOFECMANIF CHAR(10 BYTE),
  CMONEDCODIGO CHAR(3 BYTE),
  CADUANCODIGO CHAR(3 BYTE),
  CUMEDICODIGO CHAR(2 BYTE),
  CENVIOFLAFORAB CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  NENVIOVALDECDEST NUMBER(10, 3),
  CMANIFESTADO CHAR(1 BYTE) DEFAULT (' ') NOT NULL,
  CRETENCODIGO CHAR(3 BYTE),
  NENVIONROBULTOS NUMBER(10, 0),
  ESUKEY CHAR(2 BYTE),
  ESUTIPC CHAR(4 BYTE),
  ESUNUM CHAR(7 BYTE),
  CCODVIA CHAR(1 BYTE),
  ORIGENENV CHAR(1 BYTE),
  HOJARCOL5 NUMBER(8, 3),
  HOJARCOL6 NUMBER(8, 3),
  HOJARCOL7 NUMBER(8, 3),
  HOJARCOL8 CHAR(12 BYTE),
  CTIPCTACODTIPO CHAR(1 BYTE),
  NROACTA CHAR(13 BYTE),
  NENVIOCIF NUMBER(8, 2),
  NENVIOTRIB NUMBER(8, 2),
  NENVIOTCAMB NUMBER(28, 3) DEFAULT (0) NOT NULL,
  NENVIOTOTSOL NUMBER(10, 2),
  CENVIOPOLIZA CHAR(6 BYTE),
  CENVIOFECNUMERA CHAR(10 BYTE),
  CENVIOFECCANCEL CHAR(10 BYTE),
  CENVIOOBSLIQUI VARCHAR2(100 BYTE),
  CDOCIDECODIGO CHAR(2 BYTE),
  CENVIONRODOCENT VARCHAR2(11 BYTE),
  CENVIOFECENTREGA CHAR(10 BYTE),
  CENVIORECIBIDOPOR VARCHAR2(50 BYTE),
  CENVIHORENTRE CHAR(5 BYTE),
  CENVIOTIPDOC CHAR(2 BYTE),
  CENVIONRODOC CHAR(11 BYTE),
  CENVIOOBSENTRE VARCHAR2(100 BYTE),
  CENVIOENTREGADO CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  CENVIOCANCELADO CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  CENVIOUSUCREA CHAR(12 BYTE),
  CENVIOFECCREA DATE DEFAULT (SYSDATE) NOT NULL,
  CENVIOUSUMODI CHAR(12 BYTE),
  CENVIOFECMODI DATE DEFAULT (SYSDATE),
  CRETENDIRECC VARCHAR2(150 BYTE),
  CENVOFICIORIGEN CHAR(4 BYTE),
  CENVIOFLAGTRANSF CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  CENVIONROTRANSF CHAR(14 BYTE),
  CFLAGACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  NENVIOVALDOLAR NUMBER(28, 2) DEFAULT (0) NOT NULL,
  CAGRUPCODIGO CHAR(2 BYTE),
  CENVIOEMBAR VARCHAR2(50 BYTE),
  CTRANSCODIGO CHAR(4 BYTE),
  CPAISTRANSITO CHAR(3 BYTE),
  CPAISDESTINO CHAR(3 BYTE),
  CREEXPEDCODI CHAR(2 BYTE),
  CREGIREFE CHAR(10 BYTE),
  CENVIOFLAGAJUST CHAR(1 BYTE) DEFAULT (' ') NOT NULL,
  CENVIOCIFAJUST NUMBER(28, 2),
  CENVIOTRIBAJUST NUMBER(28, 2),
  CENVIOTCAMBIOAJUST NUMBER(28, 3),
  CENVIOTOTAJUST NUMBER(28, 2),
  CCONFNRO CHAR(10 BYTE),
  CENVIOCLASE CHAR(1 BYTE) DEFAULT (0) NOT NULL,
  CENVIOFECDEP CHAR(10 BYTE),
  CENVIOTRANSFTP VARCHAR2(50 BYTE),
  CTRAMITAD CHAR(1 BYTE) DEFAULT (' ') NOT NULL,
  CFLAGRETENIDO CHAR(1 BYTE) DEFAULT ('N'),
  CFLAFACTASENASA CHAR(1 BYTE) DEFAULT ('N'),
  CFLAGACTAADUANA CHAR(1 BYTE) DEFAULT ('N'),
  CTIPOACTAADUANA CHAR(1 BYTE) DEFAULT ('0'),
  CNROACTAADUANA VARCHAR2(10 BYTE),
  CFLAGDECLSIMPF CHAR(1 BYTE) DEFAULT ('0'),
  CNRODECSIMPF VARCHAR2(10 BYTE),
  CFLAGTIPOSOLIC CHAR(1 BYTE) DEFAULT ('0'),
  CNROSOLICITUD VARCHAR2(10 BYTE),
  CFLGAMOTIVODEV CHAR(1 BYTE) DEFAULT ('0'),
  CFLAGINSTEXPED CHAR(1 BYTE) DEFAULT ('0'),
  CNROLISTADODEVOL CHAR(5 BYTE),
  CFLAGCARTALEGAJO CHAR(1 BYTE) DEFAULT ('N'),
  CTIPOCARTALEGAJO CHAR(1 BYTE) DEFAULT ('0'),
  CNROCARTALEGAJO VARCHAR2(10 BYTE),
  CNROPRECINTO CHAR(6 BYTE),
  NENVIOCANTIDAD NUMBER(10, 0) DEFAULT (0),
  CNOMCLIENTE VARCHAR2(20 BYTE),
  CTIPOENVASE CHAR(1 BYTE),
  CENVIONROCARGO NUMBER(10, 0),
  CENVIOREZAGO CHAR(1 BYTE),
  CFLAGEMPRESARIAL CHAR(1 BYTE) DEFAULT ('N'),
  CMOTCODIGO CHAR(2 BYTE),
  CCODPOSTREF CHAR(6 BYTE),
  CCLIECOD CHAR(3 BYTE),
  CSECTOR CHAR(2 BYTE),
  CSIMCODCLI CHAR(12 BYTE),
  CENVIONTOAVISODEV CHAR(8 BYTE),
  NENVIOVALDEGDEV NUMBER(18, 5),
  NENVIOCAMBIODEV NUMBER(18, 3),
  CENVIOHORADEP CHAR(5 BYTE),
  CFLAGACTATRASLADO CHAR(1 BYTE),
  CNROACTATRASLADO VARCHAR2(10 BYTE),
  CCOBCODIGO CHAR(7 BYTE),
  NTARCODIGO NUMBER(10, 0),
  CVENTRANSAC CHAR(12 BYTE),
  CENVIOPESOEXPENDIO NUMBER(10, 0),
  CENVIOCANAL CHAR(1 BYTE),
  CENVIONOMAUX VARCHAR2(50 BYTE),
  CENVIONROCOMP CHAR(10 BYTE),
  NENVIOFOB NUMBER(8, 2),
  CENVIOFLAGEXPIMP CHAR(1 BYTE),
  CENVIODESPACHADOR VARCHAR2(50 BYTE),
  CENVIOCODAFORADOR CHAR(6 BYTE),
  CENVIOCODOPERADOR CHAR(6 BYTE),
  CENVIOFECSALIDA CHAR(10 BYTE),
  CENVIOHORSALIDA CHAR(5 BYTE),
  CENVIODOCDISPOSICION CHAR(15 BYTE),
  CENVIOTIPCOMP CHAR(2 BYTE),
  CENVIOINCDESP VARCHAR2(100 BYTE),
  NCLICODIGO NUMBER(10, 0),
  CENVIOFLAGREGDIST CHAR(1 BYTE),
  NSESREFE NUMBER(18, 0),
  NTRANSACODIGO NUMBER(28, 0),
  CODBARRA CHAR(18 BYTE),
  CDEVUELTO CHAR(1 BYTE) DEFAULT ('N'),
  NCLADIR1CODIGOEMI NUMBER(19, 0),
  NCLADIR2CODIGOEMI NUMBER(19, 0),
  NCLADIR3CODIGOEMI NUMBER(19, 0),
  CEMICALLE VARCHAR2(60 BYTE),
  CEMIDIRENRO VARCHAR2(10 BYTE),
  CEMIDPTONRO VARCHAR2(10 BYTE),
  CEMIZONANOMB VARCHAR2(60 BYTE),
  NCLADIR1CODIGODEST NUMBER(19, 0),
  NCLADIR2CODIGODEST NUMBER(19, 0),
  NCLADIR3CODIGODEST NUMBER(19, 0),
  CDESTCALLE VARCHAR2(60 BYTE),
  CDESTDIRENRO VARCHAR2(10 BYTE),
  CDESTDPTONRO VARCHAR2(10 BYTE),
  CDESTZONANOMB VARCHAR2(60 BYTE),
  CDESTDIRECREFE VARCHAR2(100 BYTE),
  CENVIOREMIDNI CHAR(11 BYTE),
  CENVIOFLAGIPS CHAR(1 BYTE),
  CFLAGEMPGLOB CHAR(1 BYTE),
  CENVIOAUDIENTREGA DATE,
  NID_ORDEN NUMBER(12, 0),
  NENVIOFLETE NUMBER(10, 3),
  NENVIOFLETEDOLAR NUMBER(10, 3),
  NID_MONEDA NUMBER(5, 0),
  NENVIOFLETEDOLARREAL NUMBER(10, 3),
  CFECAPEUPUEMS CHAR(10 BYTE),
  CHORAPEUPUEMS CHAR(5 BYTE),
  INDDESP VARCHAR2(2 BYTE),
  CODFUNADUA VARCHAR2(4 BYTE),
  CODFUNSERPOST VARCHAR2(6 BYTE),
  CENVIOFECLLEGA_D DATE,
  CENVIOFECAPERT_D DATE,
  CENVIOFECMANIF_D DATE,
  CENVIOFECNUMERA_D DATE,
  CENVIOFECCANCEL_D DATE,
  CENVIOFECENTREGA_D DATE,
  CENVIOFECDEP_D DATE,
  CENVIOFECSALIDA_D DATE,
  CFECAPEUPUEMS_D DATE,
  CENVIOFECCREA_D DATE,
  IDERROR NUMBER(7, 0),
  CESTADO VARCHAR2(1 BYTE),
  CONSTRAINT CENVIOREFE PRIMARY KEY (CENVIOREFE),
  CONSTRAINT NID_MONEDA FOREIGN KEY (NID_MONEDA)
    REFERENCES SOP.STA_MONEDA(NID_MONEDA),
  CONSTRAINT NID_ORDEN FOREIGN KEY (NID_ORDEN)
    REFERENCES SOP.STA_ORDEN(NID_ORDEN))
TABLESPACE SOP_DATA2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
LOGGING
ENABLE ROW MOVEMENT;

CREATE INDEX SOP.IDX_CENVIOFECCREA ON SOP.SOPENVIOS (CENVIOFECCREA)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE INDEX SOP.IDX_SENV ON SOP.SOPENVIOS (TRIM("CENVIONROORIGEN"))
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING UNUSABLE;

CREATE INDEX SOP.IDX$$_0DCE0001 ON SOP.SOPENVIOS (CENVIOANIO, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IDX$$_0F030001 ON SOP.SOPENVIOS (SUBSTR("CENVIOFECNUMERA",4,7), CADUANCODIGO, CENVIOFLAFORAB, CENVIOENTREGADO, CENVIOCANCELADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IND05 ON SOP.SOPENVIOS (CENVIONROORIGEN)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;

CREATE INDEX SOP.IND06 ON SOP.SOPENVIOS (CENVIONROAVISOLL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_DEVOLUCION ON SOP.SOPENVIOS (CENVIOANIO, CTIPOENVIO, CENVIOESTADO, CENVIONTOAVISODEV)
TABLESPACE SOP_IDX
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO08 ON SOP.SOPENVIOS (CENVIONROTRANSF)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO10 ON SOP.SOPENVIOS (CFLAGEMPRESARIAL, CENVIOANIO, CTIPOENVIO, CTIPAQCODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO11 ON SOP.SOPENVIOS (CENVIOANIO, CTIPOENVIO, CENVIONROORIGEN, CENVIOESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO13 ON SOP.SOPENVIOS (CENVIOANIO, CTIPOENVIO, CENVIONROAVISOLL, CENVIOESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO14 ON SOP.SOPENVIOS (CFLAGEMPRESARIAL, CENVIOFLAFORAB, CENVIOANIOMAN, CENVIONROMAN, CTIPOENVIO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO15 ON SOP.SOPENVIOS (CENVIOANIO, CENVIOFLAFORAB, CTIPOENVIO, CADUANCODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO20 ON SOP.SOPENVIOS (CTIPOENVIO, CENVIOUSUCREA, CENVIOFECCREA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO27 ON SOP.SOPENVIOS (CENVIONROORIGEN, CENVIOESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO30 ON SOP.SOPENVIOS (CTIPOENVIO, CENVIOESTADO, CAGRUPCODIGO, CENVIOFECAPERT, CENVIOFLAFORAB, CADUANCODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO31 ON SOP.SOPENVIOS (CTIPOENVIO, CENVIOANIO, CCODPOSTAL, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXENVIO32 ON SOP.SOPENVIOS (CENVIOCANCELADO, CENVIOFLAFORAB, CENVIOFECCANCEL, CTRAMITAD)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_ESTADISTICA ON SOP.SOPENVIOS (CTIPOENVIO, CFLAGEMPRESARIAL, CENVIOFECCREA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXEV_001 ON SOP.SOPENVIOS (CENVIOANIO, CENVIONROORIGEN, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXEV_002 ON SOP.SOPENVIOS (CENVIOANIO, CTIPOENVIO, CENVIONROORIGEN, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXEV_003 ON SOP.SOPENVIOS (CENVIOANIO, CTIPOENVIO, CENVIOREMITEN, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXEV_004 ON SOP.SOPENVIOS (CENVIOANIO, CENVIOREMITEN, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXEV_005 ON SOP.SOPENVIOS (CENVIOANIO, CTIPOENVIO, CENVIODESTINA, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXEV_006 ON SOP.SOPENVIOS (CENVIOANIO, CENVIODESTINA, CFLAGEMPRESARIAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXEV_007 ON SOP.SOPENVIOS (CENVIONROAVISOLL, CENVIOANIO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_ORDEN ON SOP.SOPENVIOS (NID_ORDEN)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_CENVIOANIO ON SOP.SOPENVIOS (CENVIOANIO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_1 ON SOP.SOPENVIOS (CVENTRANSAC)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_11 ON SOP.SOPENVIOS (CTIPOENVIO, CENVIOFECCREA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS12 ON SOP.SOPENVIOS (CTIPOENVIO, CENVIOANIO, CENVIOESTADO, CENVIOFLAGIPS)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_3 ON SOP.SOPENVIOS (CENVIOFECAPERT, CENVIOFLAFORAB)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_5 ON SOP.SOPENVIOS (CENVIOANIO, CENVIOFLAFORAB, CENVIOCANCELADO, NENVIOTRIB, CTIPOENVIO, CAGRUPCODIGO, CENVIOFECCANCEL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_7 ON SOP.SOPENVIOS (NTRANSACODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_8 ON SOP.SOPENVIOS (CREGIREFE, CTIPOENVIO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_SOPENVIOS_9 ON SOP.SOPENVIOS (CENVOFICIORIGEN, CENVIOFLAGREGDIST, CTIPOENVIO, CVENTRANSAC)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IX_TRANSFPROV ON SOP.SOPENVIOS (CENVIOFLAFORAB, CTIPOENVIO, CENVIOFECMANIF)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND10 ON SOP.SOPENVIOS (CTIPOENVIO, CENVIOFLAFORAB, CENVIOENTREGADO, CENVIONROORIGEN)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND11 ON SOP.SOPENVIOS (CTIPOENVIO, CENVIOFLAFORAB, CENVIOENTREGADO, CCODPOSTAL)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND12 ON SOP.SOPENVIOS (CENVIOANIO, CTIPOENVIO, CENVIONROORIGEN, CVENTRANSAC)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND13 ON SOP.SOPENVIOS (CENVIOANIO, CENVIODESTINA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;