CREATE TABLE SOP.SOPDESPACHO (
  CDESPAREFE CHAR(14 BYTE) NOT NULL,
  CREGIREFE CHAR(10 BYTE),
  CTDESPCODI CHAR(1 BYTE),
  CSERVICODIGO CHAR(2 BYTE) NOT NULL,
  CSUBCLCODIGO CHAR(2 BYTE),
  COFICIORIGEN CHAR(4 BYTE),
  COFICITRANSITO VARCHAR2(20 BYTE),
  COFICIDESTINO CHAR(4 BYTE),
  CCATEGCODIGO CHAR(2 BYTE) NOT NULL,
  CADUACODIGO CHAR(3 BYTE),
  CDESPANUMERO CHAR(6 BYTE) NOT NULL,
  CTRANSCODIGO CHAR(4 BYTE),
  CDESPAANIO CHAR(4 BYTE) NOT NULL,
  CDESPAFEXPED DATE,
  CDESPAFECEXPED CHAR(10 BYTE) NOT NULL,
  CDESPAFLLEGA DATE,
  CDESPAFECLLEGA CHAR(10 BYTE) NOT NULL,
  CDESPAHORARECEP CHAR(5 BYTE),
  CDESPANROVUELO VARCHAR2(40 BYTE) DEFAULT (' '),
  CDESPAFECARRIVO CHAR(10 BYTE) DEFAULT (' ') NOT NULL,
  NDESPANROSACR NUMBER(10, 0) DEFAULT (0),
  NDESPANROSACB NUMBER(10, 0) DEFAULT (0),
  NDESPANROSACMR NUMBER(10, 0) DEFAULT (0),
  NDESPANROSACMB NUMBER(10, 0) DEFAULT (0),
  NDESPANROSACVACIA NUMBER(10, 0) DEFAULT (0),
  NDESPATOTSACACANJE NUMBER(10, 0) DEFAULT (0),
  NDESPATOTSACATARJA NUMBER(10, 0) DEFAULT (0),
  NDESPAPESOSUJEPAGO NUMBER(20, 3) DEFAULT (0),
  NDESPAPESOEXENPAGO NUMBER(20, 3) DEFAULT (0),
  NDESPAM5PESO NUMBER(10, 0) DEFAULT (0),
  NDESPAM5CANT NUMBER(10, 0) DEFAULT (0),
  NDESPAM5MASPESO NUMBER(10, 0) DEFAULT (0),
  NDESPAVACIASPESO NUMBER(10, 0) DEFAULT (0),
  NDESPAPESOFACT NUMBER(20, 2) DEFAULT (0),
  NDESPANROENVCERT NUMBER(10, 0) DEFAULT (0),
  NDESPANROENVVALD NUMBER(10, 0) DEFAULT (0),
  NDESPANROPAQCERT NUMBER(10, 0) DEFAULT (0),
  NDESPANROPAQVALD NUMBER(10, 0) DEFAULT (0),
  NDESPATOTENVCERTI NUMBER(10, 0) DEFAULT (0),
  NDESPATOTENVVALD NUMBER(10, 0) DEFAULT (0),
  NDESPATOTENVCERTIEXE NUMBER(10, 0) DEFAULT (0),
  NDESPATOTENVVALDEXE NUMBER(10, 0) DEFAULT (0),
  NDESPCN33 NUMBER(10, 0) DEFAULT (0),
  NDESPCN33LLEG NUMBER(10, 0) DEFAULT (0),
  NDESPCN16 NUMBER(10, 0) DEFAULT (0),
  NDESPCN16LLEG NUMBER(10, 0) DEFAULT (0),
  NDESPCN65 NUMBER(10, 0) DEFAULT (0),
  NDESPCN65LLEG NUMBER(10, 0) DEFAULT (0),
  CDESPABOLPRUEBA CHAR(1 BYTE) DEFAULT ('0') NOT NULL,
  CDESPANROCONTAIN VARCHAR2(30 BYTE) DEFAULT (' ') NOT NULL,
  CDESPANROPRECIN VARCHAR2(30 BYTE) DEFAULT (' ') NOT NULL,
  NDESPADUPLICADO NUMBER(10, 0) DEFAULT (0),
  CDESPAREMESA CHAR(1 BYTE),
  CDESPUSUCREA CHAR(12 BYTE),
  CDESPUSUMODI CHAR(12 BYTE),
  DDESPUSUFECCREA DATE DEFAULT (SYSDATE) NOT NULL,
  DDESPUSUFECMODI DATE,
  NDESPAPESOCANJE NUMBER(20, 2) DEFAULT (0) NOT NULL,
  NDESPAPESOTARJA NUMBER(20, 2) DEFAULT (0) NOT NULL,
  CPUERTCODIGO CHAR(5 BYTE),
  CDESPAINDICACION VARCHAR2(250 BYTE),
  CBDVREFE CHAR(6 BYTE),
  CBDVTIPO CHAR(4 BYTE),
  CDESPAESTADO CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  CAGRUPCODIGO CHAR(2 BYTE),
  CITINEREF CHAR(10 BYTE),
  CDESPAFALTANTE CHAR(1 BYTE),
  CDESPAFACTURA CHAR(14 BYTE),
  CDESPANROBDV VARCHAR2(10 BYTE),
  CCLIECOD CHAR(3 BYTE),
  CDESPAFALTAF NUMBER(10, 0) DEFAULT (0) NOT NULL,
  CDESPAFALTAR NUMBER(10, 0) DEFAULT (0) NOT NULL,
  CDESPAFALTAB NUMBER(10, 0) DEFAULT (0) NOT NULL,
  CDESPAFALTAMH5 NUMBER(10, 0) DEFAULT (0) NOT NULL,
  CDESPAFALTAMM5 NUMBER(10, 0) DEFAULT (0) NOT NULL,
  CDESPAFALTAENV NUMBER(10, 0) DEFAULT (0) NOT NULL,
  CDESPAFALTPESOF NUMBER(20, 2) DEFAULT (0) NOT NULL,
  CDESPAFALTPESOR NUMBER(20, 2) DEFAULT (0) NOT NULL,
  CDESPAFALTPESOB NUMBER(20, 2) DEFAULT (0) NOT NULL,
  CDESPAFALTPESOMH5 NUMBER(20, 2) DEFAULT (0) NOT NULL,
  CDESPAFALTPESOMM5 NUMBER(20, 2) DEFAULT (0) NOT NULL,
  CDESPAFALTPESOENV NUMBER(20, 2) DEFAULT (0) NOT NULL,
  CDESPAITEM CHAR(3 BYTE),
  CFLAGAV2 CHAR(1 BYTE),
  CMALENCREFE CHAR(7 BYTE),
  CNUMCN65 CHAR(5 BYTE),
  NLISTA NUMBER(10, 0),
  NORDEN NUMBER(10, 0),
  CHECK ("CSUBCLCODIGO" IS NOT NULL) DISABLE,
  CHECK ("COFICIORIGEN" IS NOT NULL) DISABLE,
  CONSTRAINT PK__SOPDESPACHO__22778171 PRIMARY KEY (CDESPAREFE),
  CONSTRAINT FK__SOPDESPAC__CAGRU__737D66BD FOREIGN KEY (CAGRUPCODIGO)
    REFERENCES SOP.SOPGRUPO(CAGRUPCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPCATEGCORREO FOREIGN KEY (CCATEGCODIGO)
    REFERENCES SOP.SOPCATEGCORREO(CCATEGCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPDEPADUANAS FOREIGN KEY (CADUACODIGO)
    REFERENCES SOP.SOPDEPADUANAS(CADUACODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPDESPACHOTIPO FOREIGN KEY (CTDESPCODI)
    REFERENCES SOP.SOPDESPACHOTIPO(CTDESPCODI) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPITINERARIO FOREIGN KEY (CITINEREF)
    REFERENCES SOP.SOPITINERARIO(CITINEREF) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPOFICINA FOREIGN KEY (COFICIORIGEN)
    REFERENCES SOP.SOPOFICINA(COFICICODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPOFICINA1 FOREIGN KEY (COFICIDESTINO)
    REFERENCES SOP.SOPOFICINA(COFICICODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPPUERTOS FOREIGN KEY (CPUERTCODIGO)
    REFERENCES SOP.SOPPUERTOS(CPUERTCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPSERVICIO FOREIGN KEY (CSERVICODIGO)
    REFERENCES SOP.SOPSERVICIO(CSERVICODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPSUBCLASCORRE FOREIGN KEY (CSUBCLCODIGO)
    REFERENCES SOP.SOPSUBCLASCORREO(CSUBCLCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPTRANSPORTIST FOREIGN KEY (CTRANSCODIGO)
    REFERENCES SOP.SOPTRANSPORTISTA(CTRANSCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPUSUARIO FOREIGN KEY (CDESPUSUCREA)
    REFERENCES SOP.SOPUSUARIO(IDUSUARIO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPDESPACHO_SOPUSUARIO1 FOREIGN KEY (CDESPUSUMODI)
    REFERENCES SOP.SOPUSUARIO(IDUSUARIO) ON DELETE CASCADE)
TABLESPACE SOP_DATA2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
LOGGING;

CREATE INDEX SOP.IDX$$_70D60001 ON SOP.SOPDESPACHO ("COFICIORIGEN"||"COFICIDESTINO"||"CCATEGCODIGO"||"CSUBCLCODIGO"||"CDESPAANIO"||"CDESPANUMERO")
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.INDDESPA_BUSQ ON SOP.SOPDESPACHO (COFICIORIGEN, COFICIDESTINO, CCATEGCODIGO, CSUBCLCODIGO, CDESPAANIO, CTDESPCODI, CSERVICODIGO, CDESPAESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA01 ON SOP.SOPDESPACHO (CDESPAFACTURA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA02 ON SOP.SOPDESPACHO (COFICIORIGEN, COFICIDESTINO, CCATEGCODIGO, CSUBCLCODIGO, CDESPAANIO, CSERVICODIGO, CTDESPCODI, CADUACODIGO, CCLIECOD, CDESPANUMERO, CDESPAESTADO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA03 ON SOP.SOPDESPACHO (CTDESPCODI, CDESPAFECLLEGA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA04 ON SOP.SOPDESPACHO (CTDESPCODI, CDESPAFEXPED, CCATEGCODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA05 ON SOP.SOPDESPACHO (CTDESPCODI, COFICIDESTINO, CDESPAFECEXPED, CSUBCLCODIGO, CDESPAFACTURA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA06 ON SOP.SOPDESPACHO (COFICIORIGEN, COFICIDESTINO, CCATEGCODIGO, CSUBCLCODIGO, CDESPAANIO, CDESPANUMERO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA07 ON SOP.SOPDESPACHO (CREGIREFE)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA08 ON SOP.SOPDESPACHO (COFICIORIGEN, CCATEGCODIGO, CSUBCLCODIGO, CADUACODIGO, CSERVICODIGO, CDESPAESTADO, CAGRUPCODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA11 ON SOP.SOPDESPACHO (CDESPAANIO, CTDESPCODI, CSERVICODIGO, CCATEGCODIGO, CDESPAFECLLEGA, CSUBCLCODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA12 ON SOP.SOPDESPACHO (CDESPAANIO, CTDESPCODI, CSERVICODIGO, CCATEGCODIGO, CDESPAFECEXPED, CSUBCLCODIGO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA13 ON SOP.SOPDESPACHO (CTDESPCODI, COFICIORIGEN)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA15 ON SOP.SOPDESPACHO (CTDESPCODI, CCATEGCODIGO, CDESPAFECEXPED)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA17 ON SOP.SOPDESPACHO (CDESPAANIO, CTDESPCODI)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.IXDESPA18 ON SOP.SOPDESPACHO (CDESPAANIO, CTDESPCODI, CDESPAFLLEGA)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

CREATE INDEX SOP.SOP_IND03 ON SOP.SOPDESPACHO (CCATEGCODIGO, CTRANSCODIGO, COFICIDESTINO, COFICIORIGEN, CSUBCLCODIGO, CDESPAANIO, CDESPANUMERO)
TABLESPACE SOP_IDX2
STORAGE (
  INITIAL 64K
  NEXT 504K
  MAXEXTENTS UNLIMITED
  PCTINCREASE 0
)
NOLOGGING;

COMMENT ON COLUMN SOP.SOPDESPACHO.CADUACODIGO IS 'CODIGO DE ADUANA --';
COMMENT ON COLUMN SOP.SOPDESPACHO.CCATEGCODIGO IS 'CODIGO DE CATEGORIA -- TABLA SOPCATEGCORREO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAANIO IS 'AÑO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAESTADO IS 'ESTADO DEL DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAFACTURA IS 'REFERENCIA DE LA TABLA SOPFACTURA';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAFECARRIVO IS 'FECHA DE ARRIVO. TIPO CHAR';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAFECEXPED IS 'FECHA DE EXPEDICION. TIPO DATE';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAFECLLEGA IS 'FECHA DE LLEGADA TIPO CHAR';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAFEXPED IS 'FECHA DE EXPEDICION. TIPO CHAR';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAFLLEGA IS 'FECHA DE LLEGADA TIPO DATE';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAHORARECEP IS 'HORA DE RECEPCION';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAITEM IS 'NUMERO DE ITEM';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPANROVUELO IS 'NRO DE VUELO DEL DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPANUMERO IS 'NUMERO DE DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPAREFE IS 'LLAVE PRIMARIA Y REFERENCIA DEL DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPUSUCREA IS 'CODIGO DE USUARIO QUE CREO EL DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CDESPUSUMODI IS 'CODIGO DE USUARIO QUE MODIFIFCO EL DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.COFICIDESTINO IS 'OFICINA DE DESTINO';
COMMENT ON COLUMN SOP.SOPDESPACHO.COFICIORIGEN IS 'OFICINA DE ORIGIEN';
COMMENT ON COLUMN SOP.SOPDESPACHO.COFICITRANSITO IS 'OFICINA DE TRANSITO';
COMMENT ON COLUMN SOP.SOPDESPACHO.CSUBCLCODIGO IS 'CODIGO DE SUB-CLASE.TABLA SOPSUBCLASCORREO';
COMMENT ON COLUMN SOP.SOPDESPACHO.DDESPUSUFECCREA IS 'FECHA DEL USUARIO QUE CREO EL DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.DDESPUSUFECMODI IS 'FECHA DEL USUARIO QUE MODIFICO DEL DESPACHO';
COMMENT ON COLUMN SOP.SOPDESPACHO.NDESPANROSACMR IS 'NUMERO DE SACA';
COMMENT ON COLUMN SOP.SOPDESPACHO.NDESPAPESOCANJE IS 'PESO DE CANJE';
COMMENT ON COLUMN SOP.SOPDESPACHO.NDESPAPESOFACT IS 'PESO X DESPACHODE LA TABLA SOPFACTURA';
COMMENT ON COLUMN SOP.SOPDESPACHO.NDESPAPESOTARJA IS 'PESO DE TARJA';
COMMENT ON COLUMN SOP.SOPDESPACHO.NDESPATOTSACACANJE IS 'CANTIDAD DE SACAS X DESPACHO EN CAJE';
COMMENT ON COLUMN SOP.SOPDESPACHO.NLISTA IS 'NUMERO DE LISTA';
COMMENT ON COLUMN SOP.SOPDESPACHO.NORDEN IS 'NUMERO DE ORDEN';