CREATE TABLE SOP.SOPSUBCLASCORREO (
  CSUBCLCODIGO CHAR(2 BYTE) NOT NULL,
  CSUBCLSIGLAS CHAR(2 BYTE),
  CSUBCLDESCRIP VARCHAR2(50 BYTE),
  CSERVICODIGO CHAR(2 BYTE),
  CSUBCLTIPO CHAR(1 BYTE) DEFAULT ('N') NOT NULL,
  CSUBCLACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CSUBCLDESCRIP_CORTO VARCHAR2(50 BYTE),
  CONSTRAINT PK_SOPSUBCLASEC_CSUBCLCODIGO PRIMARY KEY (CSUBCLCODIGO),
  CONSTRAINT FK_SOPSUBCLASCORREO_SOPSERVICI FOREIGN KEY (CSERVICODIGO)
    REFERENCES SOP.SOPSERVICIO(CSERVICODIGO) ON DELETE CASCADE)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;

CREATE INDEX SOP.IXSUBCLAS01 ON SOP.SOPSUBCLASCORREO (CSUBCLSIGLAS)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;