CREATE TABLE SOP.SOPITINERARIO (
  CITINEREF CHAR(10 BYTE) NOT NULL,
  CTRANSCODIGO CHAR(4 BYTE) NOT NULL,
  CPUERTCODIGO CHAR(5 BYTE) NOT NULL,
  COFICICODIGO CHAR(4 BYTE),
  CCUADROCODIGO CHAR(2 BYTE),
  CITINENROVUELO VARCHAR2(30 BYTE),
  CITINETIPCORREO VARCHAR2(10 BYTE),
  CITINEENLACE1 VARCHAR2(30 BYTE),
  CITINEENLACE2 VARCHAR2(30 BYTE),
  CITINEDIASAL CHAR(1 BYTE),
  CITINEHORVUELO CHAR(5 BYTE),
  CITINEHORCIERRE CHAR(5 BYTE),
  CITINEDIALLE CHAR(1 BYTE),
  CITINEVIA VARCHAR2(30 BYTE),
  CITINEHORLLE CHAR(5 BYTE),
  CITINETIPO CHAR(1 BYTE),
  CITINECLASE CHAR(1 BYTE),
  CITINEACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CITINEUSUCREA CHAR(12 BYTE),
  CITINEFECCREA DATE DEFAULT (SYSDATE) NOT NULL,
  CITINEUSUMODI CHAR(12 BYTE),
  CITINEFECMODI DATE,
  CONSTRAINT PK_SOPITINERARIO_CITINEREF PRIMARY KEY (CITINEREF),
  CONSTRAINT FK_SOPITINERARIO_SOPCUADROS FOREIGN KEY (CCUADROCODIGO)
    REFERENCES SOP.SOPCUADROS(CCUADROCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPITINERARIO_SOPOFICINA FOREIGN KEY (COFICICODIGO)
    REFERENCES SOP.SOPOFICINA(COFICICODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPITINERARIO_SOPPUERTOS FOREIGN KEY (CPUERTCODIGO)
    REFERENCES SOP.SOPPUERTOS(CPUERTCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPITINERARIO_SOPTRANSPORTI FOREIGN KEY (CTRANSCODIGO)
    REFERENCES SOP.SOPTRANSPORTISTA(CTRANSCODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPITINERARIO_SOPUSUARIO FOREIGN KEY (CITINEUSUCREA)
    REFERENCES SOP.SOPUSUARIO(IDUSUARIO) ON DELETE CASCADE,
  CONSTRAINT FK_SOPITINERARIO_SOPUSUARIO1 FOREIGN KEY (CITINEUSUMODI)
    REFERENCES SOP.SOPUSUARIO(IDUSUARIO) ON DELETE CASCADE)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;