CREATE TABLE SOP.SOPSECTOR (
  CSECTREFE NUMBER(10, 0) NOT NULL,
  CSECTCODIGO VARCHAR2(3 BYTE) NOT NULL,
  CSECTNOMBRE VARCHAR2(60 BYTE) NOT NULL,
  COFICICODIGO CHAR(4 BYTE) NOT NULL,
  CMENSAREFE CHAR(10 BYTE),
  CAGENREFE NUMBER(19, 0),
  CSECTACTIVO NUMBER(10, 0) DEFAULT (1) NOT NULL,
  CONSTRAINT PK_SOPSECTOR PRIMARY KEY (CSECTREFE),
  CONSTRAINT FK_SOPSECTOR_ADMAGENTEPOSTAL FOREIGN KEY (CAGENREFE)
    REFERENCES SOP.ADMAGENTEPOSTAL(CAGENREFE) ON DELETE CASCADE,
  CONSTRAINT FK_SOPSECTOR_SOPMENSAJERO FOREIGN KEY (CMENSAREFE)
    REFERENCES SOP.SOPMENSAJERO(CMENSAREFE) ON DELETE CASCADE)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;