CREATE TABLE SOP.SOPPUERTOS (
  CPUERTCODIGO CHAR(5 BYTE) NOT NULL,
  CPUERTTIPO CHAR(1 BYTE) NOT NULL,
  CPUERTSIGLA CHAR(5 BYTE) NOT NULL,
  CPAISCODIGO CHAR(3 BYTE) NOT NULL,
  CPUERTNOMBRE VARCHAR2(100 BYTE),
  CPUERTFECINI CHAR(10 BYTE),
  CPUERTFECFIN CHAR(10 BYTE),
  CPUERTACTIVO CHAR(1 BYTE) DEFAULT ('1') NOT NULL,
  CONSTRAINT PK__SOPPUERTOS__2C3393D0 PRIMARY KEY (CPUERTCODIGO),
  CONSTRAINT FK_SOPPUERTOS_SOPPAISES FOREIGN KEY (CPAISCODIGO)
    REFERENCES SOP.SOPPAISES(CPAISCODIGO) ON DELETE CASCADE)
TABLESPACE SOP_DATA
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;